services:
  src:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: npm run start
#    restart: always
    volumes:
      - ./logs:/app/logs
      - ./config.json:/app/config.json

volumes:
    logs: